apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: testarc1998.azurecr.io/whiplash98/spring-petclinic:117:#{Build.BuildId}#
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-svc
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
